<a href="https://colab.research.google.com/github/Ibraheem101/tensorflow/blob/main/tf_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [63]:
print(tf.__version__)

2.8.2


In [64]:
# Creating tensors with tf.constant()
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [65]:
scalar.ndim

0

In [66]:
vector = tf.constant([3, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [67]:
vector.ndim

1

In [68]:
matrix = tf.constant([[2, 4],
                      [7,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [7, 5]], dtype=int32)>

In [69]:
matrix.ndim

2

In [70]:
another_matrix = tf.constant([[4., 5],
                              [6, 7],
                              [8, 9]], dtype = tf.float16)

In [71]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float16)>

In [72]:
another_matrix.ndim

2

In [73]:
random1 = tf.random.Generator.from_seed(28)
random1 = random1.uniform(shape = (3, 2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.1337657 , 0.95617914],
       [0.6482675 , 0.55495536],
       [0.02367401, 0.74084485]], dtype=float32)>

In [74]:
random2 = tf.random.Generator.from_seed(28)
random2 = random2.uniform(shape = (3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.1337657 , 0.95617914],
       [0.6482675 , 0.55495536],
       [0.02367401, 0.74084485]], dtype=float32)>

In [75]:
tf.random.set_seed(2)
tf.random.shuffle(random1) #Randomly shuffles along first dimension

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.02367401, 0.74084485],
       [0.6482675 , 0.55495536],
       [0.1337657 , 0.95617914]], dtype=float32)>

In [76]:
tf.ones((3, 4), tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [77]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
tensor = tf.constant(arr, shape = (6,4))

In [79]:
tensor[:2, :]

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])>

In [80]:
tf.add(tensor, 19)

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30],
       [31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42]])>

In [81]:
tf.divide(tensor, 3)

<tf.Tensor: shape=(6, 4), dtype=float64, numpy=
array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667],
       [4.        , 4.33333333, 4.66666667, 5.        ],
       [5.33333333, 5.66666667, 6.        , 6.33333333],
       [6.66666667, 7.        , 7.33333333, 7.66666667]])>

In [82]:
tf.subtract(tensor, 4)

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [83]:
tf.random.set_seed(2)
tensor2 = tf.random.uniform(shape = (4, 5))
tensor2

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.14690244, 0.46425676, 0.22489977, 0.35288846, 0.9857408 ],
       [0.99910235, 0.5648881 , 0.16375077, 0.9890269 , 0.681414  ],
       [0.9361813 , 0.76035094, 0.8557707 , 0.42701852, 0.3893944 ],
       [0.69739926, 0.6512991 , 0.08290601, 0.3726778 , 0.06093955]],
      dtype=float32)>

In [84]:
tensor = tf.cast(tensor, tf.float32)
tensor

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]], dtype=float32)>

In [85]:
tf.matmul(tensor, tensor2)

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[ 4.9636626,  4.0394874,  2.12401  ,  2.9610975,  1.6430215],
       [16.082005 , 13.802668 ,  7.4333196, 11.527544 , 10.112976 ],
       [27.200346 , 23.565847 , 12.742628 , 20.09399  , 18.582932 ],
       [38.318687 , 33.329025 , 18.051937 , 28.660439 , 27.052887 ],
       [49.437027 , 43.09221  , 23.361248 , 37.226887 , 35.522842 ],
       [60.55537  , 52.855385 , 28.670555 , 45.793335 , 43.992798 ]],
      dtype=float32)>

In [86]:
tf.matmul(tensor, tf.reshape(tensor, shape = (4,6)))

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[  84.,   90.,   96.,  102.,  108.,  114.],
       [ 228.,  250.,  272.,  294.,  316.,  338.],
       [ 372.,  410.,  448.,  486.,  524.,  562.],
       [ 516.,  570.,  624.,  678.,  732.,  786.],
       [ 660.,  730.,  800.,  870.,  940., 1010.],
       [ 804.,  890.,  976., 1062., 1148., 1234.]], dtype=float32)>

In [87]:
tf.reshape(tensor, shape = (4,6)) == tf.transpose(tensor)

<tf.Tensor: shape=(4, 6), dtype=bool, numpy=
array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True]])>

In [88]:
a = tf.constant([[2,3,4]], dtype = tf.float64)
import time
start = time.time()
tf.matmul(a, tf.transpose(a))
stop = time.time()
stop - start

0.0031316280364990234

In [89]:
a = tf.constant([[2,3,4]], dtype = tf.float16)
import time
start = time.time()
tf.matmul(a, tf.transpose(a))
stop = time.time()
stop - start

0.0026082992553710938

In [92]:
a = tf.range(1, 50)
a

<tf.Tensor: shape=(49,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int32)>

In [100]:
print(tf.math.reduce_variance(tensor))

tf.Tensor(47.916668, shape=(), dtype=float32)


We can use the tensorflow_probability method to find the variance

In [101]:
import tensorflow_probability as tfp
tfp.stats.variance(a)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [103]:
rr = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
rr.std()

14.142135623730951

In [114]:
tfp.stats.quantiles(a, num_quantiles = 2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 25, 49], dtype=int32)>

In [117]:
tf.math.reduce_std(tf.cast(a, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=14.142136>

Positional indices

In [118]:
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [119]:
tf.argmin(a)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [120]:
a[tf.argmin(a)]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Squeezing a tensor removes excess single dimensions

In [125]:
b = tf.random.normal(shape = (1, 1, 1, 1, 1, 7, 30))
b

<tf.Tensor: shape=(1, 1, 1, 1, 1, 7, 30), dtype=float32, numpy=
array([[[[[[[-0.34978473,  1.680089  ,  0.64659107, -0.29098207,
             -0.12802337,  0.518896  ,  1.1973747 , -0.05563127,
              0.03263566, -0.9991939 ,  0.374411  , -1.8285949 ,
              0.8633099 , -0.79411805,  0.080853  ,  0.24617971,
             -0.68470347,  0.41752756,  0.79680616, -1.2343662 ,
             -0.9258844 ,  0.3451366 , -0.09576283, -0.47167897,
             -0.35761774,  0.07558876, -0.68658787, -0.6012635 ,
             -0.4107167 ,  0.7793978 ],
            [ 1.0165774 , -1.5505939 , -0.02059542, -0.5029889 ,
              2.1898649 ,  0.2484269 ,  0.2483165 , -0.86587507,
              1.1253623 , -0.6572555 ,  0.6485831 ,  1.4811958 ,
             -0.2484313 ,  0.22006355, -0.89698315,  0.25377867,
              0.05105684, -0.10148685, -1.7639831 , -1.042224  ,
              0.3798997 , -0.67544043,  0.4922789 , -0.40091836,
             -2.5551975 , -0.9653216 ,  0.02713482,

In [126]:
b_squeezed = tf.squeeze(b)
b_squeezed

<tf.Tensor: shape=(7, 30), dtype=float32, numpy=
array([[-0.34978473,  1.680089  ,  0.64659107, -0.29098207, -0.12802337,
         0.518896  ,  1.1973747 , -0.05563127,  0.03263566, -0.9991939 ,
         0.374411  , -1.8285949 ,  0.8633099 , -0.79411805,  0.080853  ,
         0.24617971, -0.68470347,  0.41752756,  0.79680616, -1.2343662 ,
        -0.9258844 ,  0.3451366 , -0.09576283, -0.47167897, -0.35761774,
         0.07558876, -0.68658787, -0.6012635 , -0.4107167 ,  0.7793978 ],
       [ 1.0165774 , -1.5505939 , -0.02059542, -0.5029889 ,  2.1898649 ,
         0.2484269 ,  0.2483165 , -0.86587507,  1.1253623 , -0.6572555 ,
         0.6485831 ,  1.4811958 , -0.2484313 ,  0.22006355, -0.89698315,
         0.25377867,  0.05105684, -0.10148685, -1.7639831 , -1.042224  ,
         0.3798997 , -0.67544043,  0.4922789 , -0.40091836, -2.5551975 ,
        -0.9653216 ,  0.02713482, -0.14000995, -2.1879094 ,  1.1107372 ],
       [ 1.0484066 ,  0.4895454 ,  0.18910104, -0.71228963,  0.53790736,


Onehot encoding tensors

In [132]:
some_list = [0,2,3,4]
tf.one_hot(some_list, depth = 5, on_value = 'True', off_value = 'False')

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False', b'False'],
       [b'False', b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'False', b'True']], dtype=object)>